import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Provider } from '../components/ui/provider';
import AuthenticationProvider from '../hook/useAuthentication';
import Header from '../components/fragment/Header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Money Track',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthenticationProvider>
          <Provider>
            <Header />
            <div
              style={{
                paddingTop: '56px',
              }}
            >
              {children}
            </div>
          </Provider>
        </AuthenticationProvider>
      </body>
    </html>
  );
}
